name: Deploy Node.js App and Azure Infra

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'
  AZURE_WEBAPP_NAME: 'mynodeapp3123'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Clean npm cache
      run: |
        rm -rf node_modules
        rm -f package-lock.json

    - name: Install dependencies
      run: |
        npm install
        npm install express@4.21.2 mssql@9.3.2 --save-exact

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Resource Group (Subscription Scope)
      uses: azure/arm-deploy@v2
      with:
          scope: subscription
          region: centralus
          template: ./src/Infra/resourceGroup.bicep
          parameters: ''
          deploymentName: create-resource-group

    - name: Deploy Infrastructure (Resource Group Scope)
      uses: azure/arm-deploy@v2
      with:
          scope: resourcegroup
          resourceGroupName: ahtaskrg324  
          template: ./src/Infra/infra.bicep
          parameters: ./src/Infra/infra.parameters.json
          deploymentName: deploy-infra
          failOnStdErr: false
          
    - name: Prepare Deployment Directory
      run: |
        mkdir deployment
        cp app.js config.js package*.json deployment/
        cp -r views public node_modules deployment/

    - name: Create Zip Archive for Deployment
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r nodeapp.zip deployment

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: nodeapp.zip
        startup-command: 'npm start'