name: Deploy Node.js App and Azure Infra

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'
  AZURE_WEBAPP_NAME: 'mynodeapp3123'
  AZURE_RESOURCE_GROUP: 'ah-infra-deployment-rg'

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Clean npm cache
      run: |
        rm -rf node_modules
        rm -f package-lock.json

    - name: Install dependencies
      run: |
        npm install
        npm install express@4.21.2 mssql@9.3.2 --save-exact

    - name: Deploy Infrastructure
      working-directory: ${{ github.workspace }}/src/Infra
      run: |
        az deployment group create \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --template-file infra.bicep \
          --parameters @infra.parameters.json


    - name: Create deployment package
      run: |
        mkdir deployment
        cp package*.json deployment/
        cp -r app.js config.js views public deployment/
        cd deployment
        npm ci --only=production
        zip -r ../nodeapp.zip ./*

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0  # Changed from v2 to v1
      with:
        name: app-build
        path: nodeapp.zip

  deploy:
    name: Deploy Application
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download artifact
      uses: actions/download-artifact@v1.0.0  # Changed from v2 to v1
      with:
        name: app-build

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: nodeapp.zip
        startup-command: 'npm start'