name: Deploy Node.js App and Azure Infra

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'
  AZURE_WEBAPP_NAME: 'mynodeapp3123'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Az Bicep Deployment
      working-directory: ${{ github.workspace }}/Infra
      run: |
        az deployment group create \
          --resource-group ah-infra-deployment-rg \
          --template-file infra.bicep \
          --parameters @infra.parameters.json

    - name: Prepare deployment package
      run: |
        # Create deployment directory
        mkdir deployment
        # Copy application files
        cp package*.json deployment/
        cp -r app.js config.js views public deployment/
        cd deployment
        # Install production dependencies
        npm ci --only=production
        # Create deployment package
        zip -r ../nodeapp.zip ./*

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: nodeapp.zip
        startup-command: 'npm start'